fixing typo

diff --git a/bin/binder b/bin/binder
--- a/bin/binder
+++ b/bin/binder
@@ -58,12 +58,31 @@ backup_and_link "home/.bashrc"           "$ORIGIN_DIR" "$DESTINY_DIR"
 backup_and_link "home/.tmux.conf"        "$ORIGIN_DIR" "$DESTINY_DIR"
 backup_and_link "home/.screenrc"         "$ORIGIN_DIR" "$DESTINY_DIR"
 backup_and_link "home/.gitconfig.sample" "$ORIGIN_DIR" "$DESTINY_DIR"
-backup_and_link "home/.aliase"           "$ORIGIN_DIR" "$DESTINY_DIR"
+backup_and_link "home/.aliases"           "$ORIGIN_DIR" "$DESTINY_DIR"
 
+# TODO: move vim initializations last
+# install yarn
 if [ ! -d "$DESTINY_DIR/.vim/bundle/vundle" ]; then
   git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
+  vim -c ":PluginInstall"
 fi;
 
+# TODO: move vim initializations last
+# install coc
+if [ ! -d "$DESTINY_DIR/.vim/bundle/coc.nvim" ]; then
+  type yarn > /dev/null
+  is_yarn_insalled=$?
+  if [ $is_yarn_insalled -eq "0" ]; then
+    cd "$DESTINY_DIR/.vim/bundle/coc.nvim"
+    yarn install && yarn build
+    vim -c ":CocInstall coc-json coc-tsserver coc-cairo"
+    cd --
+  else
+    echo "yarn not found: coc will not be installed"
+  fi;
+fi;
+
+# TODO: move submodules up
 cd "$ORIGIN_DIR" || exit
 
 git submodule init
